# Generated by Django 5.1.4 on 2025-03-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='role',
            field=models.CharField(choices=[('user', 'Usuário'), ('admin', 'Administrador')], default='user', max_length=10),
        ),
    ]
