# Generated by Django 5.1.4 on 2025-04-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarda',
            name='data_guarda',
            field=models.DateTimeField(),
        ),
    ]
