# Generated by Django 5.1.4 on 2025-03-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0002_usuariocustomizado_tipo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='escala_horario',
            field=models.TimeField(),
        ),
    ]
